#!/usr/bin/env bash
# Restart Nginx to apply the new configuration
# Create a backup of the default Nginx configuration
# Use sed to replace the default Nginx configuration with a new configuration that includes a custom 404 page

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo sed -i '/server_name _;/a \\\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t\treturn 404 "Ceci n'\''est pas une page";\n\t}\n' /etc/nginx/sites-available/default

sudo service nginx restart
